twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'custom.form.html.twig'
    paths:
        'templates/layouts': 'layouts'
        #"%kernel.project_dir%/../assets/js/components/Editor2":editor
    exception_controller: null
    globals:
        enable_shibboleth: '%app.shibboleth.enable%'
        contact_mail: '%app.general.contact_mail%'